# Generated by Django 4.1 on 2022-08-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ips',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('enderecoIP', models.CharField(max_length=20)),
            ],
        ),
    ]
