# Generated by Django 4.1 on 2022-08-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedIps',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bannedIPs', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='ips',
            old_name='enderecoIP',
            new_name='IPs',
        ),
    ]
