# Generated by Django 4.1 on 2022-08-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_bannedips_id_alter_ips_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannedips',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ips',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
