# Generated by Django 4.1 on 2022-08-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_bannedips_bannedips_alter_ips_ips'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannedips',
            old_name='bannedIPs',
            new_name='IPs',
        ),
    ]
